### PR TITLE
Fix for the issue 173

### PR DESCRIPTION
**Pull request by pasupulaphani**

### CODE REVIEW

**Comment by yassineAlouini** [comment]
Please merge this pull request!

**Comment by conor-mac-aoidh** [comment]
This is a very annoying bug.. +1 merge!

**Comment by borNfreee** [comment]
Seems like the author @diegonetto is not interested in this project anymore (look at his profile and activity). Time to think about fork or using other generators...

**Comment by pasupulaphani** [comment]
May be Yeoman guys are interested in taking ownership? or someone?

Sad to see things dying.

**Pull request merged**
