### PR TITLE
Merged fixes and improvisations from all active forks.

### PR DESCRIPTION
**Pull request by SidneyS**
A combination of all current fixes from the most active forks to make a stress free start easier.

### CODE REVIEW

**Comment by diegonetto** [comment]
@SidneyS I've reviewing this and testing it locally. There are some updates to the README that were specific to @JaKXz's fork. I'm not sure what else might have been overlooked, but I'd like to get this pulled in today.

**Comment by JaKXz** [comment]
@diegonetto @SidneyS I *believe* the only README difference is the installation instructions [to use `npm link`]. Otherwise, for the most part (of what I can remember I've done) is add ngCordova and some defaults that I like. :)

**Comment by diegonetto** [comment]
@JaKXz Thanks for chiming in, I can confirm that's all I saw as well.

A few spot checks I do when testing new PR's is to create a new project and run the following:
```
grunt serve
grunt platform:add:ios
grunt serve:compress
grunt emulate:ios
grunt ripple
grunt karma
grunt coverage
grunt jshint
npm test
```

It looks like the following aren't working as intended:
```
grunt serve:compress   - stylesheets not loading
grunt karma            - unable to find angular
grunt coverage         - fails because karma fails 
npm test               - hangs on watch task
```

Can someone please confirm my findings?

Thanks,
DN

**Comment by SidneyS** [comment]
Hi DN,

great to hear from you - finally, the master to the rescue :-) I fixed the css issues, and added complete 'wiredap' replacements for the current Ionic templates (see comments). Regexing is of couse prone to errors (if they should choose to change the syntax), but more maintainable than the old proprietary templates approach. We could also fix the templates revision to a changeset diff to ensure this.

The test stuff remains then.

**Comment by SidneyS** [comment]
Also fixed the test stuff, and some less obvious bugs.

**Comment by SidneyS** [comment]
@dschi Thanks, merged in those as well.

**Comment by diegonetto** [comment]
Thanks everyone for contributing. If someone can confirm that the hooks are properly functioning I will merge this into the master branch and push a new release this evening.

**Comment by SidneyS** [comment]
Fixed all mocha unit tests, removed some bloat. Continous Integration Server / Travis is happy again. @diegonetto: Thanks!

**Comment by diegonetto** [comment]
@SidneyS Thanks for all your hard work!

Please follow the [contributing docs](https://github.com/diegonetto/generator-ionic/blob/master/contributing.md) commit conventions next time. They are parsed to update the [CHANGELOG.md](https://github.com/diegonetto/generator-ionic/blob/master/CHANGELOG.md) when we push new releases.

**Comment by diegonetto** [comment]
I should have been more careful with this, since it looks someone deleted the project's Gruntfile that was used to push new releases to npm and I didn't notice. I'll add it back in...

**Comment by diegonetto** [comment]
Okay version `0.7.0` is out. @SidneyS or @JaKXz if one of ya'll could spare a moment, could you close any remaining open issues that were addressed by commits in this massive merge?

**Comment by JaKXz** [comment]
@diegonetto I can take a look at issues I've opened, sure. Thanks for taking the time to do all this, @SidneyS and @diegonetto et al!

**Comment by JaKXz** [comment]
*append to my previous comment:* it would be nice, however, if someone documented all the changes that have been made and updated the README with where the generator is now.

**Pull request merged**
